// Traducciones al inglés de las pantallas del panel web (apps/admin/src).
// La clave es el texto en español tal como aparece en el código; las variables {x} se mantienen.
export const EN_ADMIN_PAGINAS: Record<string, string> = {
  // Menú y marco (App.tsx)
  "Panel": "Dashboard",
  "Furgones": "Vans",
  "Rutas": "Routes",
  "Conductoras": "Drivers",
  "Cobros": "Payments",
  "Solicitudes": "Requests",
  "Preguntas frecuentes": "FAQ",
  "Llamadas y costos": "Calls & costs",
  "Configuración": "Settings",
  "Administración": "Admin",
  "Menú": "Menu",
  "Secciones": "Sections",
  "conductora": "driver",
  "Cerrar sesión": "Sign out",
  "Modo demostración · datos de ejemplo, los cambios no se guardan al recargar": "Demo mode · sample data, changes are lost when you reload",

  // Componentes comunes
  "Cargando…": "Loading…",
  "Cerrar": "Close",
  "Copia el texto:": "Copy the text:",
  "Copiado": "Copied",
  "Copiar": "Copy",
  "Copiar mensaje": "Copy message",
  "Código para la familia": "Code for the family",
  "Enviar por WhatsApp": "Send via WhatsApp",
  "Hola. Para recibir los avisos del furgón de {alumno}:\n1) Descarga la app «Furgón Escolar».\n2) Toca «Crear cuenta» y escribe este código: {codigo}\n¡Listo! Te avisaremos unos 5 minutos antes de que llegue el furgón.":
    "Hi! To get school van alerts for {alumno}:\n1) Download the “Furgón Escolar” app.\n2) Tap “Create account” and enter this code: {codigo}\nThat's it! We'll let you know about 5 minutes before the van arrives.",
  "El código sirve para ambos apoderados y vence en 60 días. La tía no tiene que hacer nada: el alumno ya aparece en su ruta.":
    "The code works for both parents and expires in 60 days. The driver doesn't need to do anything: the student is already on their route.",
  "Contacto principal": "Primary contact",
  "Contacto secundario (opcional)": "Secondary contact (optional)",
  "Ej: Ana (mamá)": "e.g. Ana (mom)",
  "Ej: Pedro (abuelo)": "e.g. Pedro (grandpa)",
  "Teléfono": "Phone",
  "Recibe la alarma y la llamada.": "Gets the alert and the call.",
  "Lo llamamos si el principal no contesta.": "We call them if the primary contact doesn't answer.",
  "© colaboradores de OpenStreetMap": "© OpenStreetMap contributors",
  "Mapa: toca o arrastra el pin para ubicar la casa": "Map: tap or drag the pin to mark the home",
  "Colegio": "School",
  "{nombre} (hoy no va)": "{nombre} (not riding today)",
  "Mapa de la ruta con las casas numeradas en orden": "Route map with the homes numbered in order",

  // Inicio de sesión y mensajes del servidor
  "Administración: alumnos, rutas, cobros y solicitudes de las familias.": "Admin: students, routes, payments and family requests.",
  "Correo": "Email",
  "Contraseña": "Password",
  "Ingresando…": "Signing in…",
  "Ingresar": "Sign in",
  "Demostración: cualquier correo y contraseña sirven.": "Demo: any email and password will work.",
  "Correo o contraseña incorrectos.": "Incorrect email or password.",
  "Sin conexión con el servidor.": "Can't reach the server.",
  "Esta cuenta no tiene permiso de administración. Pídeselo al administrador principal.": "This account doesn't have admin access. Ask the main administrator for it.",
  "No se pudo calcular la recomendación.": "Couldn't calculate the suggestion.",

  // Panel
  "{mes} · todo lo que necesita tu atención, en un vistazo.": "{mes} · everything that needs your attention, at a glance.",
  "Cifras principales": "Key figures",
  "Furgones activos · {n} niños": "Active vans · {n} kids",
  "Licencias que requieren atención": "Driver's licenses that need attention",
  "Solicitudes abiertas": "Open requests",
  "Cobrado este mes": "Collected this month",
  "Por cobrar este mes": "Still to collect this month",
  "Alumnos con pago vencido": "Students with overdue payments",
  "Llamadas con costo ({min} min)": "Paid calls ({min} min)",
  "Pendientes": "Pending",
  "Ver": "View",
  "Todo al día.": "All caught up.",
  "Licencia de {conductor}": "{conductor}'s driver's license",
  "Licencia de {conductor}: vence en {dias} días": "{conductor}'s driver's license: expires in {dias} days",
  "Licencia de {conductor}: vencida (no puede iniciar recorridos)": "{conductor}'s driver's license: expired (can't start trips)",
  "Licencia de {conductor}: por verificar": "{conductor}'s driver's license: pending review",
  "Licencia de {conductor}: rechazada, debe subirla de nuevo": "{conductor}'s driver's license: rejected, must upload it again",
  "Licencia de {conductor}: no la ha subido": "{conductor}'s driver's license: not uploaded yet",
  "{n} solicitud(es) de familias sin responder": "{n} unanswered family request(s)",
  "{n} alumno(s) sin ruta asignada": "{n} student(s) without a route",
  "{n} familia(s) aún no instalan la app (envíales su código)": "{n} family(ies) haven't installed the app yet (send them their code)",
  "{n} alumno(s) con mensualidad vencida": "{n} student(s) with an overdue monthly fee",
  "Recorridos de hoy": "Today's trips",
  "{n} en curso": "{n} in progress",
  "Aún no parte ningún recorrido hoy.": "No trips have started today yet.",
  "salió {hora}": "left at {hora}",
  "{atendidos}/{total} alumnos atendidos · {avisos} avisos enviados": "{atendidos}/{total} students served · {avisos} alerts sent",
  "En curso": "In progress",
  "Terminado": "Finished",
  "Ver todos": "View all",
  "Sin tía o tío": "No driver",
  "{alumnos} niños": "{alumnos} kids",
  "sin rutas": "no routes",
  "Cobranza del mes": "This month's collections",
  "{pct}% cobrado": "{pct}% collected",
  "Cobrado {monto}": "Collected {monto}",
  "Pendiente {monto}": "Pending {monto}",
  "Llamadas del mes": "This month's calls",
  "{pct}% gratis": "{pct}% free",
  "{pct}% por la app": "{pct}% through the app",
  "Por la app (sin costo) {n}": "Through the app (free) {n}",
  "Telefónicas (con costo) {n}": "Phone (paid) {n}",

  // Furgones y licencias
  "Cada furgón con su tía o tío, sus rutas, cuántos niños lleva y la licencia de quien conduce.":
    "Each van with its driver, its routes, how many kids it carries and the driver's license.",
  "+ Agregar furgón": "+ Add van",
  "Agregar furgón": "Add van",
  "Sin conductora": "No driver",
  "Licencia vigente": "License valid",
  "Licencia vigente hasta {fecha}": "License valid until {fecha}",
  "Licencia vence en {d} día": "License expires in {d} day",
  "Licencia vence en {d} días": "License expires in {d} days",
  "Licencia vencida": "License expired",
  "Licencia por verificar": "License pending review",
  "Licencia rechazada": "License rejected",
  "Sin licencia": "No license",
  "Motivo: {motivo}": "Reason: {motivo}",
  "Pídele que la suba desde su app (Inicio → Mi licencia).": "Ask them to upload it from their app (Home → My license).",
  "Revisar": "Review",
  "Aún no hay furgones. Agrega el primero con su patente y su tía o tío.": "No vans yet. Add the first one with its license plate and driver.",
  "Furgón {patente}": "Van {patente}",
  "Patente {patente}": "License plate {patente}",
  "Inactivo": "Inactive",
  "Furgón": "Van",
  "Sin tía o tío asignado": "No driver assigned",
  "Niños": "Kids",
  "{pct}% de ocupación": "{pct}% occupied",
  "Editar": "Edit",
  "Licencia": "License",
  "Furgón {patente} guardado.": "Van {patente} saved.",
  "Licencia de {conductor} aprobada.": "{conductor}'s driver's license approved.",
  "Licencia de {conductor} rechazada: se le pedirá subirla de nuevo.": "{conductor}'s driver's license rejected: they'll be asked to upload it again.",
  "Patente": "License plate",
  "Capacidad (asientos)": "Capacity (seats)",
  "Modelo y color": "Model and color",
  "Hyundai H1 blanca": "White Hyundai H1",
  "Tía o tío a cargo": "Assigned driver",
  "Sin asignar": "Unassigned",
  "Rutas que hace este furgón": "Routes this van runs",
  "Furgón activo": "Van active",
  "Guardar": "Save",
  "Cancelar": "Cancel",
  "Reverso de la licencia": "Back of the license",
  "Frente de la licencia": "Front of the license",
  "Número": "Number",
  "Clase": "Class",
  "Vence": "Due",
  "Situación": "Status",
  "Comprueba que el nombre, la clase (A1 o A3 para transporte escolar) y el vencimiento coincidan con la foto.":
    "Check that the name, the class (A1 or A3 for school transport) and the expiration date match the photo.",
  "Motivo del rechazo (lo verá la tía)": "Reason for rejection (the driver will see it)",
  "Ej: la foto está borrosa": "e.g. the photo is blurry",
  "Rechazar licencia": "Reject license",
  "Volver": "Back",
  "Aprobar licencia": "Approve license",
  "Rechazar…": "Reject…",

  // Rutas
  "El orden de las paradas es el que sigue la tía y el que usa el sistema para calcular cuándo avisar a cada familia. Usa «Recomendar ruta» para calcular el orden más corto con las direcciones de los alumnos.":
    "The stop order is the one the driver follows and the one the system uses to decide when to alert each family. Use “Suggest route” to work out the shortest order from the students' addresses.",
  "Casas → colegio": "Homes → school",
  "Colegio → casas": "School → homes",
  "sale {hora}": "leaves at {hora}",
  "Conductora": "Driver",
  "Calculando la mejor ruta…": "Calculating the best route…",
  "Recomendar ruta": "Suggest route",
  "Sin ubicación del colegio: se ordena solo entre las casas.": "No school location: only the homes are ordered.",
  "Sin alumnos todavía.": "No students yet.",
  "Hoy no va": "Not riding today",
  "Sí va hoy": "Riding today",
  "Subir a {nombre}": "Move {nombre} up",
  "Bajar a {nombre}": "Move {nombre} down",
  "Quitar": "Remove",
  "Hoy la tía se salta 1 casa: la ruta de hoy se actualiza sola y esa familia no recibe aviso. Mañana vuelve al orden normal.":
    "Today the driver skips 1 home: today's route updates automatically and that family gets no alert. Tomorrow it goes back to the usual order.",
  "Hoy la tía se salta {n} casas: la ruta de hoy se actualiza sola y esa familia no recibe aviso. Mañana vuelve al orden normal.":
    "Today the driver skips {n} homes: today's route updates automatically and those families get no alert. Tomorrow it goes back to the usual order.",
  "Agregar alumno a {ruta}": "Add student to {ruta}",
  "Agregar alumno a esta ruta…": "Add a student to this route…",
  "Agregar al final": "Add at the end",
  "{n} alumnos": "{n} students",
  "{n} no va hoy": "{n} not riding today",
  "{n} no van hoy": "{n} not riding today",
  "Calculada por calles con Google Maps.": "Calculated along streets with Google Maps.",
  "Calculada por distancia entre las casas (aproximada).": "Calculated by distance between homes (approximate).",
  "El orden actual ya es el más corto (≈ {km}).": "The current order is already the shortest (≈ {km}).",
  "Ruta recomendada": "Suggested route",
  "en vez de": "instead of",
  "ahorras": "you save",
  "(≈ {min} min por recorrido)": "(≈ {min} min per trip)",
  "Revisa el orden: tú conoces las calles y los horarios de cada familia.": "Review the order: you know the streets and each family's schedule.",
  "igual": "same",
  "antes {n}°": "was #{n}",
  "Aplicar este orden": "Apply this order",
  "Descartar": "Discard",

  // Conductoras
  "Hola. Descarga la app «Furgón Escolar», toca «Crear cuenta» y usa el código {codigo}. Tus rutas y alumnos ya están cargados: solo tienes que tocar «Iniciar recorrido».":
    "Hi! Download the “Furgón Escolar” app, tap “Create account” and use the code {codigo}. Your routes and students are already loaded: just tap “Start trip”.",
  "La tía solo instala la app y entra con su código. Los alumnos y el orden de la ruta los administras tú.":
    "The driver just installs the app and signs in with their code. You manage the students and the route order.",
  "+ Invitar conductora": "+ Invite driver",
  "Código de invitación": "Invite code",
  "Sirve una sola vez y vence en 30 días. Después asígnale sus rutas en «Rutas».": "It can be used once and expires in 30 days. Then assign their routes in “Routes”.",
  "Administra": "Can manage",
  "Sin rutas": "No routes",
  "Sí": "Yes",
  "No": "No",
  ": la tía puede agregar alumnos, ordenar su ruta, registrar pagos y responder a las familias desde su app (y entrar a este panel con su cuenta). Esa sección se bloquea mientras maneja.":
    ": the driver can add students, reorder their route, record payments and reply to families from their app (and sign in to this dashboard with their account). That section is locked while driving.",
  "Solo tú puedes dar o quitar este permiso.": "Only you can grant or remove this permission.",
  "Solo el administrador principal puede cambiar estos permisos.": "Only the main administrator can change these permissions.",
  "La ubicación del furgón es la del celular de la conductora: no se necesita un GPS aparte. Se comparte solo mientras tiene un recorrido iniciado.":
    "The van's location comes from the driver's phone: no separate GPS is needed. It's only shared while a trip is in progress.",

  // Cobros
  "Tu contabilidad: mensualidades por mes. Pon el precio de cada alumno, genera el mes una vez y marca los pagos a medida que llegan.":
    "Your bookkeeping: monthly fees by month. Set each student's price, generate the month once and mark payments as they come in.",
  "Mes anterior": "Previous month",
  "Mes siguiente": "Next month",
  "Este mes ya tenía generados los cobros de todos los alumnos activos.": "Charges for all active students were already generated for this month.",
  "Cobros de {mes} generados.": "Charges for {mes} generated.",
  "Generar cobros del mes": "Generate this month's charges",
  "Vista": "View",
  "Cobros del mes": "Monthly charges",
  "Precios": "Prices",
  "Total del mes": "Month total",
  "Cobrado": "Collected",
  "Pendiente": "Pending",
  "Vencidos": "Overdue",
  "Vencido": "Overdue",
  "Filtro": "Filter",
  "Todos": "All",
  "Pagados": "Paid",
  "Pagado": "Paid",
  "Anulado": "Voided",
  "Aún no hay cobros para {mes}. Usa «Generar cobros del mes».": "No charges for {mes} yet. Use “Generate this month's charges”.",
  "Alumno": "Student",
  "Monto": "Amount",
  "Estado": "Status",
  "Pago": "Payment",
  "Registrar pago": "Record payment",
  "Cambiar monto": "Change amount",
  "Anulado por administración": "Voided by admin",
  "Cobro anulado.": "Charge voided.",
  "Anular": "Void",
  "Monto de {alumno}": "Amount for {alumno}",
  "Solo cambia este cobro. Para cambiar el precio de todos los meses, usa «Precios».": "Only this charge changes. To change the price for every month, use “Prices”.",
  "Monto (CLP)": "Amount (CLP)",
  "Motivo (opcional)": "Reason (optional)",
  "Ej: medio mes, descuento hermanos": "e.g. half month, sibling discount",
  "Cobro de {alumno}: ahora {monto}.": "Charge for {alumno}: now {monto}.",
  "Guardar monto": "Save amount",
  "Pago de {alumno}": "Payment from {alumno}",
  "Medio de pago": "Payment method",
  "Transferencia": "Bank transfer",
  "Efectivo": "Cash",
  "Tarjeta": "Card",
  "Otro": "Other",
  "Nota (opcional)": "Note (optional)",
  "Ej: N° de transferencia": "e.g. transfer number",
  "Pago de {alumno} registrado.": "Payment from {alumno} recorded.",
  "Precio de {nombre}: {monto} al mes.": "Price for {nombre}: {monto} per month.",
  "Precio de {nombre}: {monto} al mes · se actualizaron {n} cobro(s) pendiente(s).": "Price for {nombre}: {monto} per month · {n} pending charge(s) updated.",
  "Ingreso mensual esperado ({n} alumnos)": "Expected monthly income ({n} students)",
  "Precio general": "Standard price",
  "cambiar": "change",
  "Aplicar también a los cobros pendientes desde {mes}": "Also apply to pending charges from {mes}",
  "Precio mensual": "Monthly price",
  "Precio mensual de {nombre}": "Monthly price for {nombre}",

  // Solicitudes
  "Preguntas, cancelaciones y cambios que envían las familias desde la app.": "Questions, cancellations and changes that families send from the app.",
  "Cancelación": "Cancellation",
  "Pregunta": "Question",
  "Cambio de datos": "Info change",
  "Reclamo": "Complaint",
  "Sin responder": "Unanswered",
  "Respondida": "Answered",
  "Cerrada": "Closed",
  "Por atender": "To handle",
  "Todas": "All",
  "No hay solicitudes por atender.": "No requests to handle.",
  "Elige una solicitud para ver la conversación.": "Pick a request to see the conversation.",
  "Cancelación aprobada": "Cancellation approved",
  "Cancelación rechazada": "Cancellation rejected",
  "Solicitud cerrada.": "Request closed.",
  "Respuesta": "Answer",
  "Escribe tu respuesta. La familia la verá en la app.": "Write your reply. The family will see it in the app.",
  "Aprobar cancelación y dar de baja": "Approve cancellation and unenroll",
  "Rechazar": "Reject",
  "Solo responder": "Just reply",
  "Responder": "Reply",
  "Responder y cerrar": "Reply and close",
  "Al aprobar, el alumno sale de las rutas (la tía deja de verlo) y se anulan sus cobros de los meses siguientes.":
    "When approved, the student is removed from the routes (the driver no longer sees them) and their charges for the following months are voided.",

  // Preguntas frecuentes
  "Las familias las ven en la app, en «Ayuda», antes de escribirte. Así llegan menos consultas repetidas.":
    "Families see them in the app under “Help” before writing to you, so you get fewer repeat questions.",
  "+ Nueva pregunta": "+ New question",
  "Editar pregunta": "Edit question",
  "Nueva pregunta": "New question",
  "Publicada (visible para las familias)": "Published (visible to families)",
  "Publicada": "Published",
  "Borrador": "Draft",
  "Despublicar": "Unpublish",
  "Publicar": "Publish",
  "Eliminar": "Delete",

  // Llamadas
  "Las llamadas por la app no tienen costo. Solo se paga la llamada telefónica cuando la familia no tenía internet.":
    "Calls through the app are free. You only pay for a phone call when the family had no internet.",
  "Llamadas por la app (sin costo)": "Calls through the app (free)",
  "Llamadas telefónicas (con costo)": "Phone calls (paid)",
  "Minutos telefónicos": "Phone minutes",
  "Costo estimado": "Estimated cost",
  "Tarifa por minuto (CLP)": "Rate per minute (CLP)",
  "Revisa la tarifa real en tu cuenta de Twilio. Es solo una estimación.": "Check the actual rate in your Twilio account. This is only an estimate.",
  "Sin llamadas en {mes}.": "No calls in {mes}.",
  "Fecha": "Date",
  "Llamado a": "Called",
  "Canal": "Channel",
  "Resultado": "Result",
  "Duración": "Duration",
  "App · gratis": "App · free",
  "Teléfono · con costo": "Phone · paid",
  "Confirmó (presionó 1)": "Confirmed (pressed 1)",
  "Sin internet → teléfono": "No internet → phone",
  "No contestó": "No answer",
  "Contestó sin confirmar": "Answered without confirming",
  "Ocupado": "Busy",
  "Falló": "Failed",
  "Cancelada": "Canceled",
  "Programada": "Scheduled",

  // Configuración
  "Datos de tu empresa y valores por defecto para los cobros.": "Your company details and default values for charges.",
  "Nombre de la empresa": "Company name",
  "Teléfono de contacto": "Contact phone",
  "Aparece en la sección Ayuda de la app.": "Shown in the app's Help section.",
  "Mensualidad por defecto (CLP)": "Default monthly fee (CLP)",
  "cada alumno puede tener la suya.": "each student can have their own.",
  "Día de vencimiento": "Due day",
  "Configuración guardada.": "Settings saved.",

  // Alumnos
  "Alumnos": "Students",
  "Agrega aquí a los alumnos de la tía: quedan en su ruta y la familia recibe un código para conectarse.":
    "Add the driver's students here: they're placed on the route and the family gets a code to connect.",
  "+ Agregar alumno": "+ Add student",
  "Buscar por nombre, curso, dirección…": "Search by name, grade, address…",
  "Buscar alumnos": "Search students",
  "Activos": "Active",
  "Sin ruta": "No route",
  "Familia sin app": "Family without app",
  "Dados de baja": "Unenrolled",
  "No hay alumnos en esta vista.": "No students in this view.",
  "Dirección": "Address",
  "Ruta": "Route",
  "Familia": "Family",
  "Mensualidad": "Monthly fee",
  "Sin dirección": "No address",
  "Sin app": "No app",
  "* Mensualidad por defecto de la empresa (se cambia en Configuración).": "* Company default monthly fee (change it in Settings).",

  // Ficha del alumno
  "Alumno no encontrado.": "Student not found.",
  "Dado de baja el {fecha}": "Unenrolled on {fecha}",
  "Dar de baja": "Unenroll",
  "Datos": "Details",
  "Nombre": "Name",
  "Curso": "Grade",
  "Mensualidad (CLP)": "Monthly fee (CLP)",
  "La de la empresa": "Company default",
  "Avisar antes de llegar": "Alert before arriving",
  "{m} minutos": "{m} minutes",
  "Datos guardados.": "Details saved.",
  "Guardar datos": "Save details",
  "sin teléfono": "no phone",
  "Usa la app": "Uses the app",
  "La familia aún no instala la app. Envíale su código.": "The family hasn't installed the app yet. Send them their code.",
  "Ver código para la familia": "Show code for the family",
  "Sin ruta. Asígnala en": "No route. Assign one in",
  "Casa": "Home",
  "Indicaciones para la tía": "Directions for the driver",
  "Casa actualizada. El próximo recorrido usará este pin.": "Home updated. The next trip will use this pin.",
  "Guardar casa": "Save home",
  "Teléfonos para los avisos": "Phones for alerts",
  "Revisa el teléfono de {nombre}.": "Check {nombre}'s phone number.",
  "Revisa el teléfono de un contacto.": "Check a contact's phone number.",
  "Debe quedar al menos un teléfono.": "At least one phone number is required.",
  "Teléfonos guardados.": "Phone numbers saved.",
  "Guardar teléfonos": "Save phone numbers",
  "Dar de baja a {nombre}": "Unenroll {nombre}",
  "Sale de todas las rutas (la tía deja de verlo) y se anulan sus cobros de los próximos meses. El historial se conserva.":
    "They're removed from all routes (the driver no longer sees them) and their charges for upcoming months are voided. The history is kept.",
  "Motivo": "Reason",
  "Ej: se cambió de colegio": "e.g. changed schools",
  "Alumno dado de baja.": "Student unenrolled.",

  // Nuevo alumno
  "{nombre} quedó registrado/a": "{nombre} has been added",
  "Ya está en la ruta de la tía. Envía este código a la familia para que reciba los avisos.": "They're already on the driver's route. Send this code to the family so they get the alerts.",
  "Ver ficha": "View profile",
  "Agregar otro alumno": "Add another student",
  "Falta el nombre.": "Name is missing.",
  "Falta la dirección.": "Address is missing.",
  "Ubica la casa en el mapa: así el aviso llega a tiempo.": "Mark the home on the map so the alert arrives on time.",
  "Revisa el número (ej: 9 1234 5678).": "Check the number (e.g. 9 1234 5678).",
  "Agrega al menos un teléfono.": "Add at least one phone number.",
  "Agregar alumno": "Add student",
  "Completa los datos una vez. La tía verá al alumno en su ruta y la familia solo tendrá que ingresar un código.":
    "Fill in the details once. The driver will see the student on their route and the family will only need to enter a code.",
  "Nombre y apellido": "Full name",
  "Ej: Sofía Pérez": "e.g. Sofía Pérez",
  "Ej: 3° Básico": "e.g. 3rd grade",
  "Vacío = la de la empresa": "Empty = company default",
  "Calle, número, comuna": "Street, number, district",
  "No encontramos la dirección: ubica el pin a mano.": "We couldn't find the address: place the pin by hand.",
  "No pudimos buscar la dirección: ubica el pin a mano.": "We couldn't search for the address: place the pin by hand.",
  "Buscando…": "Searching…",
  "Buscar": "Search",
  "Indicaciones para la tía (opcional)": "Directions for the driver (optional)",
  "Ej: portón verde, depto 302": "e.g. green gate, apt 302",
  "Toca el mapa o arrastra el pin hasta la puerta de la casa. El aviso de 5 minutos se calcula hasta este punto.":
    "Tap the map or drag the pin to the front door. The 5-minute alert is calculated to this point.",
  "sin conductora": "no driver",
  "Queda al final de la ruta; puedes cambiar el orden en «Rutas».": "They're added at the end of the route; you can change the order in “Routes”.",
  "Guardando…": "Saving…",
  "Guardar alumno": "Save student",
};
