// Traducciones al inglés de la app móvil: familias (apoderado), ingreso y registro, cuenta,
// componentes compartidos, notificaciones y ubicación. Texto en español → inglés.
export const EN_MOVIL_FAMILIAS: Record<string, string> = {
  // Inicio de sesión, registro y cuenta
  "Avisos automáticos de llegada": "Automatic arrival alerts",
  "Correo": "Email",
  "Contraseña": "Password",
  "Ingresar": "Sign in",
  "¿La mamá o el papá te compartió a los hijos?": "Did a mom or dad share their children with you?",
  "👨‍👩‍👧 Entrar con código de familia": "👨‍👩‍👧 Sign in with a family code",
  "¿Tienes un código de invitación? Crea tu cuenta": "Have an invite code? Create your account",
  "apoderado": "parent",
  "conductor": "driver",
  "administrador": "administrator",
  "Revisa el teléfono (ej: 9 1234 5678).": "Check the phone number (e.g. 9 1234 5678).",
  "La contraseña debe tener al menos 8 caracteres.": "Your password must be at least 8 characters.",
  "Crear cuenta": "Create account",
  "Creas tu cuenta como familia. Después buscas a tu tía o tío del furgón y te conectas con un toque.": "You'll create your account as a family. Then you find your school van driver and connect with one tap.",
  "Si el furgón te dio un código de invitación, escríbelo: define si te registras como apoderado o conductor.": "If your school van gave you an invite code, enter it: it decides whether you sign up as a parent or a driver.",
  "Tengo un código de invitación": "I have an invite code",
  "Código de invitación": "Invite code",
  "Soy familia y no tengo código": "I'm a family and don't have a code",
  "Te unirás a \"{empresa}\" como {rol}.": "You'll join \"{empresa}\" as a {rol}.",
  "Código no válido o vencido.": "Invalid or expired code.",
  "Nombre y apellido": "First and last name",
  "Teléfono": "Phone",
  "Mínimo 8 caracteres": "At least 8 characters",
  "Ya tengo cuenta": "I already have an account",
  "Al crear tu cuenta aceptas los términos y condiciones, y que tratemos tus datos y los de tus hijos para el transporte escolar según la política de privacidad.": "By creating your account, you accept the terms and conditions and agree that we process your data and your children's data for school transportation as described in the privacy policy.",
  "Revisa tu teléfono (ej: 9 1234 5678): lo usamos para la llamada automática.": "Check your phone number (e.g. 9 1234 5678): we use it for the automatic call.",
  "Entrar con código": "Sign in with a code",
  "Escribe el código que te compartió la mamá o el papá. Entrarás directo a la familia: verás a los mismos hijos y recibirás los avisos del furgón en este teléfono.": "Enter the code the mom or dad shared with you. You'll go straight into the family: you'll see the same children and get the school van alerts on this phone.",
  "Código de familia": "Family code",
  "Te unirás a {familia}.": "You'll join {familia}.",
  "Código no válido, vencido o ya usado.": "Invalid, expired, or already used code.",
  "Tu nombre": "Your name",
  "Ej: Rodrigo Pérez": "E.g. Rodrigo Pérez",
  "Tu teléfono": "Your phone",
  "Para llamarte si no contestan el aviso.": "So we can call you if no one answers the alert.",
  "Entrar": "Sign in",
  "Al entrar aceptas los términos y condiciones, y que tratemos tus datos para el transporte escolar según la política de privacidad.": "By signing in, you accept the terms and conditions and agree that we process your data for school transportation as described in the privacy policy.",
  "Cuenta sin perfil": "Account without a profile",
  "Tu cuenta existe, pero no está asociada a ningún furgón. Pide al administrador un código de invitación y regístrate con él, o vuelve a intentarlo si ya te lo asignaron.": "Your account exists, but it isn't linked to any school van. Ask the administrator for an invite code and sign up with it, or try again if they've already added you.",
  "Reintentar": "Try again",
  "Cerrar sesión": "Sign out",
  "Eliminar mi cuenta": "Delete my account",
  "Términos y condiciones": "Terms and conditions",
  "Política de privacidad": "Privacy policy",
  "Correo o contraseña incorrectos.": "Incorrect email or password.",
  "Sin conexión. Revisa tu señal e intenta de nuevo.": "No connection. Check your signal and try again.",
  "Ya existe una cuenta con ese correo.": "An account with that email already exists.",
  "No se pudo crear la cuenta. Revisa el código de invitación.": "We couldn't create the account. Check the invite code.",

  // Eliminar cuenta
  "ELIMINAR": "DELETE",
  "Tu perfil, tu correo, tu teléfono y tus preferencias.": "Your profile, email, phone number, and preferences.",
  "El servicio «{empresa}» completo: 1 alumno, sus rutas, cobros e historial.": "The entire “{empresa}” service: 1 student, its routes, charges, and history.",
  "El servicio «{empresa}» completo: {n} alumnos, sus rutas, cobros e historial.": "The entire “{empresa}” service: {n} students, its routes, charges, and history.",
  "1 familia dejará de recibir avisos. Avísales antes.": "1 family will stop getting alerts. Let them know first.",
  "{n} familias dejarán de recibir avisos. Avísales antes.": "{n} families will stop getting alerts. Let them know first.",
  "1 hijo que solo está en tu cuenta se da de baja del furgón: se borran su dirección y contactos, y sale de la ruta. Sus cobros quedan registrados para el transportista.": "1 child who is only on your account will be removed from the school van: their address and contacts are deleted and they're taken off the route. Their charges stay on record for the transport provider.",
  "{n} hijos que solo están en tu cuenta se dan de baja del furgón: se borran su dirección y contactos, y salen de la ruta. Sus cobros quedan registrados para el transportista.": "{n} children who are only on your account will be removed from the school van: their addresses and contacts are deleted and they're taken off the route. Their charges stay on record for the transport provider.",
  "Los hijos que compartes con otro familiar siguen en su cuenta; solo se quita tu teléfono de las llamadas.": "Children you share with another family member stay on their account; only your phone number is removed from the calls.",
  "Tu licencia de conducir y sus fotos. Los recorridos que hiciste quedan en el historial del servicio, sin tu nombre.": "Your driver's license and its photos. Trips you drove stay in the service history, without your name.",
  "Esto no se puede deshacer.": "This can't be undone.",
  "Se borrará:": "What will be deleted:",
  "Los registros de cobros que la ley obliga a guardar y los respaldos de seguridad se eliminan dentro de 30 días.": "Charge records we're required by law to keep and security backups are deleted within 30 days.",
  "Ver la política de privacidad": "View the privacy policy",
  "Para confirmar, escribe {palabra}": "To confirm, type {palabra}",
  "Eliminar mi cuenta para siempre": "Delete my account forever",

  // Inicio de la familia
  "Avisarme con anticipación de…": "Alert me ahead of time by…",
  "{n} minutos": "{n} minutes",
  "Cancelar": "Cancel",
  "Hola, {nombre}": "Hi, {nombre}",
  "Salir": "Sign out",
  "¿Salir sin proteger tu cuenta?": "Sign out without securing your account?",
  "Entraste con un código: si sales ahora, no podrás volver a entrar. Protégela primero con tu correo.": "You signed in with a code: if you sign out now, you won't be able to get back in. Secure it with your email first.",
  "Proteger mi cuenta": "Secure my account",
  "Salir igual": "Sign out anyway",
  "🔒 Protege tu cuenta": "🔒 Secure your account",
  "Entraste con un código. Agrega tu correo y una contraseña para no perderla si cambias de teléfono.": "You signed in with a code. Add your email and a password so you don't lose it if you change phones.",
  "Agregar correo y contraseña": "Add email and password",
  "🤝 Conéctate con tu tía o tío del furgón": "🤝 Connect with your school van driver",
  "Búscalo por su nombre o comuna y envíale una solicitud. Cuando la acepte, registras a tus hijos y empiezas a recibir los avisos.": "Search by name or area and send a request. Once they accept, you add your children and start getting alerts.",
  "Buscar a mi tía o tío": "Find my driver",
  "Me compartieron un código de la familia": "Someone shared a family code with me",
  "Aún no registras alumnos. Agrega a tu hijo/a con su dirección exacta para recibir los avisos.": "You haven't added any students yet. Add your child with their exact address to get alerts.",
  "🤝 Una tía o tío quiere conectarse contigo": "🤝 A driver wants to connect with you",
  "🤝 {n} tías o tíos quieren conectarse contigo": "🤝 {n} drivers want to connect with you",
  "🌅 Recorrido de ida en curso": "🌅 Morning trip in progress",
  "🏠 Recorrido de vuelta en curso": "🏠 Afternoon trip in progress",
  "Subió al furgón desde las {hora} ✅": "On the van since {hora} ✅",
  "En su hogar desde las {hora} ✅": "Home since {hora} ✅",
  "Marcado ausente por el conductor": "Marked absent by the driver",
  "Hoy no viaja": "Not riding today",
  "🔔 Llega en ~{min} min (aviso {hora})": "🔔 Arriving in ~{min} min (alert at {hora})",
  "Te avisaremos cuando el furgón esté cerca.": "We'll alert you when the van is close.",
  "🚐 {nombre} va a bordo desde las {hora}": "🚐 {nombre} has been on board since {hora}",
  "🙋 Ya subió {nombre}": "🙋 {nombre} is on board",
  "🗺️ Seguir a {nombre} en vivo": "🗺️ Track {nombre} live",
  "🗺️ Seguir el furgón en vivo": "🗺️ Track the van live",
  "Recibido, estoy atento/a": "Got it, I'm ready",
  "Ida (mañana)": "To school (morning)",
  "Vuelta (tarde)": "Home (afternoon)",
  "Aviso {min} min antes · cambiar": "Alert {min} min ahead · change",
  "💳 Pagos": "💳 Payments",
  "💬 Ayuda": "💬 Help",
  "👨‍👩‍👧 Familia: compartir con papá o mamá": "👨‍👩‍👧 Family: share with dad or mom",
  "🤝 Conectar con mi tía o tío": "🤝 Connect with my driver",
  "+ Registrar alumno": "+ Add student",

  // Ayuda y consultas
  "Pregunta": "Question",
  "Cambio de datos": "Update details",
  "Reclamo": "Complaint",
  "Cancelar el servicio": "Cancel the service",
  "Enviada": "Sent",
  "Respondida": "Answered",
  "Cerrada": "Closed",
  "Escribe un asunto y tu mensaje.": "Enter a subject and your message.",
  "Elige qué alumno deja el furgón.": "Choose which student is leaving the van.",
  "Ayuda": "Help",
  "Volver": "Back",
  "Nueva consulta": "New request",
  "La administración revisará tu solicitud y te confirmará desde cuándo queda cancelado el servicio.": "The office will review your request and confirm when the service will be canceled.",
  "Asunto": "Subject",
  "Mensaje": "Message",
  "Enviar": "Send",
  "+ Escribir a la administración": "+ Write to the office",
  "Mis consultas": "My requests",
  "Otro": "Other",
  "Preguntas frecuentes": "FAQ",
  "¿Urgente? Llama a la administración al {telefono}.": "Urgent? Call the office at {telefono}.",
  "Consulta": "Request",
  "Cancelación aprobada.": "Cancellation approved.",
  "Cancelación rechazada.": "Cancellation declined.",
  "Tú": "You",
  "Administración": "Management",
  "Escribe tu mensaje": "Write your message",
  "Esta consulta está cerrada. Si necesitas algo más, escribe una nueva desde Ayuda.": "This request is closed. If you need anything else, start a new one from Help.",

  // Conectar con la tía o tío
  "Conectar con tu tía o tío": "Connect with your driver",
  "🤝 {nombre} quiere conectarse contigo": "🤝 {nombre} wants to connect with you",
  "Aceptar": "Accept",
  "Listo: ya estás conectado/a con {nombre}. Ahora registra a tus hijos.": "Done: you're now connected with {nombre}. Now add your children.",
  "Rechazar": "Decline",
  "Invitación rechazada.": "Invite declined.",
  "Buscar tía o tío del furgón": "Find your school van driver",
  "Nombre, furgón o comuna": "Name, van, or area",
  "Escribe al menos 2 letras. Solo aparecen quienes activaron «Que las familias me encuentren».": "Type at least 2 letters. Only drivers who turned on “Let families find me” appear.",
  "No encontramos a nadie con «{texto}». Pídele a tu tía o tío que active la búsqueda en su app, o que te envíe un código.": "We couldn't find anyone matching “{texto}”. Ask your driver to turn on search in their app, or to send you a code.",
  "✓ Conectados": "✓ Connected",
  "Solicitud enviada · esperando respuesta": "Request sent · waiting for a reply",
  "Mensaje (opcional)": "Message (optional)",
  "Ej: Hola tía, Sofía va en 3° básico": "E.g. Hi! Sofía is in 3rd grade",
  "Enviar solicitud": "Send request",
  "Solicitud enviada a {nombre}. Te avisaremos cuando responda.": "Request sent to {nombre}. We'll let you know when they reply.",
  "🤝 Conectar": "🤝 Connect",
  "Solicitudes enviadas": "Sent requests",
  "{empresa} · esperando respuesta": "{empresa} · waiting for a reply",
  "Retirar solicitud": "Withdraw request",
  "Solicitud retirada.": "Request withdrawn.",
  "Conectado/a con": "Connected with",

  // Familia (perfil compartido)
  "Papá": "Dad",
  "Mamá": "Mom",
  "Abuelo/a": "Grandparent",
  "{a} y {b}": "{a} and {b}",
  "Elige al menos un hijo/a.": "Choose at least one child.",
  "Hola. Te comparto a {nombres} en la app «Furgón Escolar» para que también recibas los avisos del furgón y lo sigas en vivo.\n1) Descarga la app.\n2) Si no tienes cuenta, toca «Crear cuenta» y escribe este código: {codigo}\n   Si ya tienes cuenta, ve a «Familia» → «Tengo un código».\nEl código sirve una vez y vence en 7 días.": "Hi! I'm sharing {nombres} with you in the “Furgón Escolar” app so you also get the school van alerts and can track it live.\n1) Download the app.\n2) If you don't have an account, tap “Create account” and enter this code: {codigo}\n   If you already have an account, go to “Family” → “I have a family code”.\nThe code works once and expires in 7 days.",
  "Código {codigo} listo. Cuando lo use, aparecerá aquí.": "Code {codigo} is ready. Once it's used, they'll show up here.",
  "Listo: ahora también recibes los avisos de {nombres}.": "Done: you now also get alerts for {nombres}.",
  "¿Dejar de recibir los avisos de {alumno}?": "Stop getting alerts for {alumno}?",
  "¿Dejar de compartir a {alumno} con {apoderado}?": "Stop sharing {alumno} with {apoderado}?",
  "Ya no verás a este hijo/a en tu app.": "You won't see this child in your app anymore.",
  "Ya no recibirá los avisos ni verá el furgón.": "They won't get alerts or see the van anymore.",
  "Dejar de compartir": "Stop sharing",
  "Listo.": "Done.",
  "Familia": "Family",
  "Comparte a tus hijos con el papá o la mamá (o un abuelo/a). Cada uno entra con su propia cuenta y ambos reciben la alarma, las llamadas, siguen el furgón en vivo y pueden marcar «Ya subió» y «hoy no viaja».": "Share your children with their dad or mom (or a grandparent). Each of you signs in with your own account, and both of you get the alarm and calls, can track the van live, and can mark “On board” and “Not riding today”.",
  "👤 Tú": "👤 You",
  "Quitar": "Remove",
  "👨‍👩‍👧 Compartir con…": "👨‍👩‍👧 Share with…",
  "¿A quiénes?": "Which children?",
  "Compartir por WhatsApp u otra app": "Share via WhatsApp or another app",
  "Se crea un código de un solo uso que vence en 7 días.": "This creates a one-time code that expires in 7 days.",
  "Tengo un código de la familia": "I have a family code",
  "Si te compartieron a los hijos, escribe aquí el código que te enviaron.": "If someone shared their children with you, enter the code they sent you here.",
  "Código": "Code",
  "Unirme": "Join",
  "Hola. Para recibir los avisos del furgón de {nombre}:\n1) Descarga la app «Furgón Escolar».\n2) Toca «Crear cuenta» y escribe este código: {codigo}\n¡Listo! Te avisaremos unos 5 minutos antes de que llegue el furgón.": "Hi! To get the school van alerts for {nombre}:\n1) Download the “Furgón Escolar” app.\n2) Tap “Create account” and enter this code: {codigo}\nThat's it! We'll alert you about 5 minutes before the van arrives.",

  // Registrar alumno
  "No encontramos esa dirección. Ubica el pin manualmente.": "We couldn't find that address. Place the pin manually.",
  "No pudimos buscar la dirección. Ubica el pin manualmente.": "We couldn't look up the address. Place the pin manually.",
  "Elige con qué tía o tío va al colegio.": "Choose which driver takes them to school.",
  "Marca en el mapa la puerta de tu casa: así el aviso será exacto.": "Mark your front door on the map so the alert is accurate.",
  "Revisa el teléfono del contacto principal.": "Check the main contact's phone number.",
  "Revisa el teléfono del contacto secundario.": "Check the backup contact's phone number.",
  "Contacto principal": "Main contact",
  "Contacto secundario": "Backup contact",
  "Registrar alumno": "Add student",
  "¿Con qué tía o tío va?": "Which driver do they ride with?",
  "Nombre del alumno": "Student's name",
  "Colegio": "School",
  "Curso": "Grade",
  "Ej: 3° Básico": "e.g. 3rd grade",
  "Dirección": "Address",
  "Calle, número, comuna": "Street, number, district",
  "Buscar en el mapa": "Find on the map",
  "Toca el mapa o arrastra el pin hasta la puerta de tu casa.": "Tap the map or drag the pin to your front door.",
  "Indicaciones para el conductor (opcional)": "Notes for the driver (optional)",
  "Ej: portón verde, depto 302": "E.g. green gate, apt 302",
  "Teléfonos para la llamada automática": "Phone numbers for the automatic call",
  "Contacto principal · nombre": "Main contact · name",
  "Contacto principal · teléfono": "Main contact · phone",
  "Contacto secundario · nombre (opcional)": "Backup contact · name (optional)",
  "Contacto secundario · teléfono": "Backup contact · phone",
  "Si el principal no contesta dos veces, llamamos a este número.": "If the main contact doesn't answer twice, we'll call this number.",
  "El administrador del furgón asignará al alumno a la ruta correspondiente.": "The school van administrator will assign the student to the right route.",
  "Guardar": "Save",

  // Pagos
  "Pagos": "Payments",
  "Tienes {monto} pendiente. Para pagar o consultar, contacta a la administración ({telefono}).": "You have {monto} due. To pay or ask a question, contact the office ({telefono}).",
  "Tienes {monto} pendiente.": "You have {monto} due.",
  "Estás al día. ¡Gracias!": "You're all paid up. Thank you!",
  "Aún no hay mensualidades registradas.": "No monthly fees recorded yet.",
  "Pagado el {fecha}": "Paid on {fecha}",
  "Vence el {fecha}": "Due {fecha}",
  "Pagado": "Paid",
  "Vencido": "Overdue",
  "Pendiente": "Pending",

  // Proteger cuenta
  "Listo: tu cuenta quedó protegida. Puedes entrar con tu correo en cualquier teléfono.": "Done: your account is secured. You can sign in with your email on any phone.",
  "Te enviamos un correo para confirmar. Cuando lo confirmes, tu cuenta quedará protegida.": "We sent you an email to confirm. Once you confirm it, your account will be secured.",
  "Protege tu cuenta": "Secure your account",
  "Entraste con un código, así que tu cuenta solo vive en este teléfono. Agrega tu correo y una contraseña para no perderla si cambias de teléfono o cierras sesión.": "You signed in with a code, so your account only exists on this phone. Add your email and a password so you don't lose it if you change phones or sign out.",

  // Llamada por la app
  "El furgón escolar está por llegar.": "The school van is about to arrive.",
  "Para confirmar, presione 1.": "To confirm, press 1.",
  "Llamada por internet · sin costo": "Internet call · free",
  "Aviso de {alumno}": "Alert for {alumno}",
  "Aviso de llegada": "Arrival alert",
  "Presionar 1 para confirmar": "Press 1 to confirm",
  "Colgar": "Hang up",
  "Si no confirmas en {seg} s, volveremos a llamar.": "If you don't confirm within {seg} s, we'll call again.",
  "✅ Aviso confirmado": "✅ Alert confirmed",
  "Llamada terminada": "Call ended",
  "Sin respuesta": "No answer",
  "Confirmar (1)": "Confirm (1)",
  "No puedo": "I can't",

  // Seguir el furgón en vivo
  "Tu hijo/a": "Your child",
  "{nombre} va rumbo al colegio": "{nombre} is on the way to school",
  "{nombre} está en su hogar": "{nombre} is home",
  "El furgón está llegando": "The van is arriving",
  "Llega en {min} min": "Arriving in {min} min",
  "Furgón en camino": "Van on the way",
  "Tu casa": "Your home",
  "Furgón": "Van",
  "‹ Volver": "‹ Back",
  "Cargando…": "Loading…",
  "Sin recorrido en curso": "No trip in progress",
  "El mapa se activa cuando la tía inicia el recorrido.": "The map turns on when the driver starts the trip.",
  "🚐 {nombre} va a bordo desde las {hora}.": "🚐 {nombre} has been on board since {hora}.",
  "Ubicación exacta en vivo.": "Exact live location.",
  "El furgón está en una parada: ubicación aproximada para cuidar la privacidad de otras familias.": "The van is at a stop: approximate location to protect other families' privacy.",
  "En su hogar desde las {hora}.": "Home since {hora}.",
  "Aviso enviado a las {hora} · confirmado ✓.": "Alert sent at {hora} · confirmed ✓.",
  "Aviso enviado a las {hora}.": "Alert sent at {hora}.",
  "El furgón está en otra parada: ubicación aproximada.": "The van is at another stop: approximate location.",
  "Falta 1 parada antes de tu casa. Ubicación aproximada.": "1 stop left before your home. Approximate location.",
  "Faltan {n} paradas antes de tu casa. Ubicación aproximada.": "{n} stops left before your home. Approximate location.",
  "Tu casa es la próxima parada. Ubicación aproximada hasta el aviso.": "Your home is the next stop. Approximate location until the alert.",
  "Salió a buscar": "Picking up",
  "Aviso": "Alert",
  "Subió": "On board",
  "En el colegio": "At school",
  "Salió del colegio": "Left school",
  "En su hogar": "Home",
  "Conductor/a": "Driver",
  "🔒 Por privacidad, la ubicación exacta se muestra solo mientras tu hijo/a va a bordo o desde tu aviso hasta la llegada.": "🔒 For privacy, the exact location is shown only while your child is on board, or from your alert until arrival.",

  // Mapa, licencia y componentes
  "Furgón escolar": "School van",
  "Parada {numero}": "Stop {numero}",
  "Tu furgón": "Your van",
  "◎ Centrar": "◎ Center",
  "Buscando tu ubicación…": "Finding your location…",
  "✓ Vigente hasta el {fecha}": "✓ Valid until {fecha}",
  "⚠ Vence en 1 día ({fecha}). Sube la renovada apenas la tengas.": "⚠ Expires in 1 day ({fecha}). Upload the renewed one as soon as you have it.",
  "⚠ Vence en {dias} días ({fecha}). Sube la renovada apenas la tengas.": "⚠ Expires in {dias} days ({fecha}). Upload the renewed one as soon as you have it.",
  "✗ Venció el {fecha}. No puedes iniciar recorridos hasta subir la renovada.": "✗ Expired on {fecha}. You can't start trips until you upload the renewed one.",
  "⏳ Enviada: la empresa la está verificando.": "⏳ Submitted: the company is reviewing it.",
  "La empresa la rechazó: {motivo}. Súbela de nuevo.": "The company rejected it: {motivo}. Please upload it again.",
  "revisa los datos": "check the details",
  "Aún no subes tu licencia. Es obligatoria para transportar niños.": "You haven't uploaded your driver's license yet. It's required to transport children.",

  // Notificaciones y ubicación
  "Aviso de llegada del furgón": "School van arrival alert",
  "Alarma cuando el furgón está a pocos minutos de tu casa": "Alarm when the school van is a few minutes from your home",
  "Novedades del recorrido": "Trip updates",
  "Alumno en su hogar, ausente y otras novedades": "Student home, absent, and other updates",
  "Ubicación del furgón": "School van location",
  "Furgón Escolar recopila la ubicación de este teléfono para compartir el furgón con las familias de tu recorrido y avisarles antes de que llegue, incluso cuando la app está cerrada o la pantalla apagada. Solo mientras hay un recorrido iniciado; al finalizarlo deja de usarla.\n\nEn la siguiente pantalla elige «Permitir todo el tiempo».": "Furgón Escolar collects this phone's location to share the van with the families on your trip and alert them before it arrives, even when the app is closed or the screen is off. Only while a trip is in progress; it stops using it when you end the trip.\n\nOn the next screen, choose “Allow all the time”.",
  "Ahora no": "Not now",
  "Continuar": "Continue",
  "Sin la ubicación del furgón no podemos avisar a las familias. Puedes iniciar el recorrido cuando quieras.": "Without the van's location we can't alert families. You can start the trip whenever you're ready.",
  "Necesitamos acceso a tu ubicación para avisar a los apoderados.": "We need access to your location to alert parents.",
  "Para avisar aunque la pantalla esté apagada, permite la ubicación \"Todo el tiempo\" en los ajustes.": "To send alerts even when the screen is off, allow location \"All the time\" in Settings.",
  "Recorrido en curso": "Trip in progress",
  "Compartiendo la ubicación del furgón con los apoderados del recorrido.": "Sharing the van's location with the parents on this trip.",
  "Salir de la familia": "Leave family",
  "la familia de {nombre}": "{nombre}'s family",
};
