// Traducciones al inglés de la app móvil: pantallas de la tía o el tío del furgón (conductor/**)
// y la pantalla de administración (admin/**).
export const EN_MOVIL_CONDUCTOR: Record<string, string> = {
  // Comunes
  "Volver": "Back",
  "Guardar": "Save",
  "Cancelar": "Cancel",
  "Aceptar": "Accept",
  "Rechazar": "Decline",
  "Cerrar": "Close",
  "Listo": "Done",
  "Buscar": "Search",
  "Salir": "Sign out",
  "Cerrar sesión": "Sign out",
  "Eliminar mi cuenta": "Delete my account",
  "Hola, {nombre}": "Hi, {nombre}",
  " y ": " and ",

  // Inicio del conductor (conductor/index.tsx)
  "Permiso de ubicación": "Location permission",
  "Inicia el recorrido antes de partir. Los avisos a los apoderados se envían solos: no necesitas tocar el teléfono mientras manejas.":
    "Start the trip before you set off. Parents get alerts automatically: you don't need to touch your phone while driving.",
  "📡 Tu celular es el GPS del furgón: mantenlo con batería, con la ubicación activada y en su soporte.":
    "📡 Your phone is the van's GPS: keep it charged, with location turned on and in its mount.",
  "🧑‍💼 Administrar": "🧑‍💼 Manage",
  "Tus alumnos, el orden de la ruta, los pagos y las consultas de las familias.":
    "Your students, the route order, payments and questions from families.",
  "Disponible cuando termines el recorrido: no se administra manejando.":
    "Available when you finish the trip: no managing while driving.",
  "Abrir administración": "Open management",
  "🪪 Mi licencia": "🪪 My license",
  "Ver mi licencia": "View my license",
  "Subir licencia": "Upload license",
  "🆕 Se sumaron a tus rutas": "🆕 New on your routes",
  "{ruta}, parada {parada}": "{ruta}, stop {parada}",
  "Quedaron donde menos alargan el recorrido. Su familia ya recibe los avisos.":
    "They were placed where they add the least to the trip. Their family already gets alerts.",
  "🤝 Conexiones con familias": "🤝 Connections with families",
  "1 familia quiere conectarse contigo.": "1 family wants to connect with you.",
  "{n} familias quieren conectarse contigo.": "{n} families want to connect with you.",
  "Busca familias o deja que te encuentren para sumarlas a tu furgón.":
    "Find families, or let them find you, to add them to your van.",
  "Abrir conexiones": "Open connections",
  "No tienes rutas asignadas.": "You have no routes assigned.",
  "Casa → colegio": "Home → school",
  "Colegio → casa": "School → home",
  "1 alumno": "1 student",
  "{n} alumnos": "{n} students",
  "Continuar recorrido en curso": "Continue current trip",
  "Iniciar recorrido": "Start trip",

  // Mi licencia (conductor/licencia.tsx)
  "Mi licencia": "My license",
  "Necesitamos permiso para la cámara o las fotos.": "We need permission to use the camera or your photos.",
  "Escribe el número de la licencia (tu RUT).": "Enter the license number (your RUT).",
  "Escribe la fecha de vencimiento como 31-12-2027.": "Enter the expiration date as day-month-year, e.g. 31-12-2027.",
  "Falta la foto del frente de la licencia.": "The photo of the front of the license is missing.",
  "Licencia enviada. Te avisaremos cuando la empresa la verifique.":
    "License sent. We'll let you know when the company verifies it.",
  "N° {numero} · Clase {clase}": "No. {numero} · Class {clase}",
  "Subir licencia renovada": "Upload renewed license",
  "Subir mi licencia": "Upload my license",
  "Número (RUT)": "Number (RUT)",
  "Clase": "Class",
  "Vence el": "Expires on",
  "Foto del frente": "Front photo",
  "Foto del reverso (opcional)": "Back photo (optional)",
  "📷 Tomar foto": "📷 Take photo",
  "🖼️ Elegir": "🖼️ Choose",
  "Enviar para verificar": "Send for verification",
  "🔒 Las fotos solo las ve la empresa para verificarla.": "🔒 Only the company sees the photos, to verify it.",

  // Conexiones (conductor/conexiones.tsx)
  "Conexiones con familias": "Connections with families",
  "{nombre} quedó conectada a tu furgón. Sus hijos entrarán solos a {rutas}, en el lugar que menos alarga el recorrido.":
    "{nombre} is now connected to your van. Their children will be added to {rutas} automatically, where they add the least to the trip.",
  "{nombre} quedó conectada a tu furgón. Sin rutas elegidas: agrégalos después en Rutas.":
    "{nombre} is now connected to your van. No routes chosen: add the children later in Routes.",
  "Invitación enviada a {nombre}. Cuando acepte: sus hijos entrarán solos a {rutas}, en el lugar que menos alarga el recorrido.":
    "Invitation sent to {nombre}. Once they accept, their children will be added to {rutas} automatically, where they add the least to the trip.",
  "Invitación enviada a {nombre}. Cuando acepte: sin rutas elegidas: agrégalos después en Rutas.":
    "Invitation sent to {nombre}. No routes chosen: once they accept, add the children later in Routes.",
  "¿En qué rutas va?": "Which routes do they ride?",
  "Aún no tienes rutas asignadas.": "You don't have any routes assigned yet.",
  "Enviar invitación": "Send invitation",
  "🤝 {nombre} quiere conectarse": "🤝 {nombre} wants to connect",
  "Solicitud rechazada.": "Request declined.",
  "Que las familias me encuentren": "Let families find me",
  "Apareces en la búsqueda con tu nombre, tu furgón y tus comunas. Nunca se muestran tu teléfono ni tus rutas.":
    "You show up in search with your name, your van and your areas. Your phone number and routes are never shown.",
  "Ahora las familias te pueden encontrar.": "Families can now find you.",
  "Ya no apareces en la búsqueda.": "You no longer appear in search.",
  "Comunas donde trabajas": "Areas (comunas) you serve",
  "Ej: Ñuñoa, La Reina, Providencia": "e.g. Ñuñoa, La Reina, Providencia",
  "Presentación (opcional)": "About you (optional)",
  "Ej: 12 años de experiencia, Colegio X": "e.g. 12 years of experience, School X",
  "Datos guardados.": "Details saved.",
  "Buscar una familia": "Find a family",
  "Por privacidad, solo con su correo o su teléfono exactos.": "For privacy, only by their exact email or phone number.",
  "Correo o teléfono": "Email or phone",
  "ana@correo.cl o 9 1234 5678": "ana@email.com or 9 1234 5678",
  "No hay una familia registrada con ese correo o teléfono. Puedes enviarle un código de invitación.":
    "No family is registered with that email or phone. You can send them an invite code.",
  "✓ Conectados": "✓ Connected",
  "Solicitud pendiente": "Request pending",
  "🤝 Invitar a conectarse": "🤝 Invite to connect",
  "Invitaciones enviadas": "Invitations sent",
  "Esperando respuesta": "Waiting for a reply",
  "Retirar invitación": "Withdraw invitation",
  "Invitación retirada.": "Invitation withdrawn.",
  "Familias conectadas ({n})": "Connected families ({n})",
  "Hijos: {hijos}": "Children: {hijos}",
  "Aún no registra a sus hijos: entrarán solos a tus rutas":
    "Hasn't added their children yet: they'll be added to your routes automatically",
  "Va en: {rutas}": "Rides on: {rutas}",

  // Recorrido en curso (conductor/recorrido/[id].tsx)
  "Pendiente": "Pending",
  "En su hogar ✅": "Home ✅",
  "Ausente": "Absent",
  "Hoy no viaja": "Not riding today",
  "Finalizar recorrido": "End trip",
  "Queda 1 alumno pendiente. ¿Finalizar de todas formas?": "1 student is still pending. End the trip anyway?",
  "Quedan {n} alumnos pendientes. ¿Finalizar de todas formas?": "{n} students are still pending. End the trip anyway?",
  "Se dejará de compartir la ubicación.": "Location sharing will stop.",
  "Finalizar": "End",
  "Subió ✅": "On board ✅",
  "Recorrido de ida": "Morning trip",
  "Recorrido de vuelta": "Afternoon trip",
  "Compartiendo ubicación": "Sharing location",
  "Compartiendo ubicación · 1 posición esperando señal": "Sharing location · 1 position waiting for signal",
  "Compartiendo ubicación · {n} posiciones esperando señal": "Sharing location · {n} positions waiting for signal",
  "✓ Su familia confirmó que subió": "✓ Their family confirmed they're on board",
  "🔔 Apoderado avisado": "🔔 Parent alerted",
  "Aún sin aviso": "Not alerted yet",
  "llegada en ~{min} min": "arriving in ~{min} min",
  "No quedan alumnos pendientes.": "No students left.",
  "Atendidos": "Done",
  "Deshacer": "Undo",

  // Administración (conductor/administrar/**)
  "Administración": "Management",
  "Tu cuenta no tiene permiso para administrar. Pídeselo al administrador principal.":
    "Your account doesn't have permission to manage. Ask the main administrator.",
  "Tienes un recorrido en curso. La administración se abre cuando lo termines: no se administra manejando.":
    "You have a trip in progress. Management opens when you finish it: no managing while driving.",
  "Los avisos a las familias siguen funcionando solos.": "Alerts to families keep working on their own.",
  "Volver al recorrido": "Back to the trip",
  "👧 Alumnos": "👧 Students",
  "1 activo": "1 active",
  "{n} activos": "{n} active",
  "1 familia sin la app": "1 family without the app",
  "{n} familias sin la app": "{n} families without the app",
  "🗺️ Rutas": "🗺️ Routes",
  "1 alumno sin ruta": "1 student without a route",
  "{n} alumnos sin ruta": "{n} students without a route",
  "Ruta recomendada, orden y «hoy no va»": "Suggested route, order and “not riding today”",
  "💳 Cobros": "💳 Payments",
  "{monto} por cobrar este mes · precios": "{monto} to collect this month · prices",
  "1 vencido": "1 overdue",
  "{n} vencidos": "{n} overdue",
  "💬 Solicitudes": "💬 Requests",
  "{n} sin responder": "{n} unanswered",
  "Todo respondido": "All answered",
  "También puedes entrar al panel web de administración con esta misma cuenta.":
    "You can also sign in to the web admin panel with this same account.",

  // Alumnos
  "Alumnos": "Students",
  "+ Agregar alumno": "+ Add student",
  "En 1 ruta": "On 1 route",
  "En {n} rutas": "On {n} routes",
  "⚠️ Sin ruta": "⚠️ No route",
  "✓ Familia usa la app": "✓ Family uses the app",
  "Familia sin la app": "Family not on the app",
  "Enviar código a la familia": "Send code to the family",

  // Nuevo alumno
  "No encontramos esa dirección: ubica el pin tocando el mapa.": "We couldn't find that address: place the pin by tapping the map.",
  "No pudimos buscar la dirección: ubica el pin tocando el mapa.": "We couldn't search for the address: place the pin by tapping the map.",
  "Falta el nombre o la dirección.": "The name or address is missing.",
  "Marca la casa en el mapa: así el aviso llega a tiempo.": "Mark the home on the map so the alert arrives on time.",
  "Revisa el teléfono principal (ej: 9 1234 5678).": "Check the main phone number (e.g. 9 1234 5678).",
  "Revisa el teléfono secundario.": "Check the secondary phone number.",
  "{nombre} quedó en tu ruta": "{nombre} is on your route",
  "Ya aparece en tu recorrido. Envía el código a la familia para que reciba los avisos.":
    "They now appear on your trip. Send the code to the family so they get alerts.",
  "Agregar alumno": "Add student",
  "Nombre y apellido": "First and last name",
  "Curso": "Grade",
  "Ej: 3° Básico": "e.g. 3rd grade",
  "Colegio": "School",
  "Dirección": "Address",
  "Calle, número, comuna": "Street, number, district",
  "Buscar en el mapa": "Find on the map",
  "Indicaciones (opcional)": "Directions (optional)",
  "Ej: portón verde": "e.g. green gate",
  "Teléfonos para los avisos": "Phone numbers for alerts",
  "Principal · nombre": "Main · name",
  "Ej: Ana (mamá)": "e.g. Ana (mom)",
  "Principal · teléfono": "Main · phone",
  "Secundario · nombre (opcional)": "Secondary · name (optional)",
  "Secundario · teléfono": "Secondary · phone",
  "Rutas": "Routes",
  "Guardar alumno": "Save student",

  // Cobros
  "efectivo": "cash",
  "transferencia": "bank transfer",
  "Cobros de {mes}": "{mes} payments",
  "Cobros del mes": "This month's charges",
  "Precios": "Prices",
  "Ingreso mensual esperado:": "Expected monthly income:",
  "Toca «Cambiar» para poner el precio de cada alumno. También se actualiza su cobro pendiente de {mes}.":
    "Tap “Change” to set each student's price. Their pending {mes} charge is updated too.",
  "Precio general": "Standard price",
  "Precio mensual de {nombre}": "Monthly price for {nombre}",
  "Precio de {nombre}: {monto} al mes.": "Price for {nombre}: {monto} per month.",
  "Cambiar precio": "Change price",
  "Cobrado:": "Collected:",
  "Por cobrar:": "To collect:",
  "Aún no se generan las mensualidades de este mes. Revisa antes los precios en «Precios».":
    "This month's fees haven't been generated yet. Check the prices in “Prices” first.",
  "Generar mensualidades del mes": "Generate this month's fees",
  "Mensualidades generadas.": "Monthly fees generated.",
  "Pagado · {medio}": "Paid · {medio}",
  "Anulado": "Canceled",
  "Vencido": "Overdue",
  "Monto de {nombre}": "Amount for {nombre}",
  "Guardar monto": "Save amount",
  "Cobro de {nombre}: ahora {monto}.": "Charge for {nombre}: now {monto}.",
  "Pagó en efectivo": "Paid in cash",
  "Pago de {nombre} registrado.": "Payment from {nombre} recorded.",
  "Transferencia": "Bank transfer",
  "Cambiar monto de este mes": "Change this month's amount",

  // Rutas
  "{nombre} no va hoy: tu ruta de hoy se salta su casa y su familia no recibe aviso.":
    "{nombre} isn't riding today: today's route skips their home and their family won't get an alert.",
  "{nombre} sí va hoy.": "{nombre} is riding today.",
  "El orden es el que sigues y el que usa el sistema para avisar a cada familia a tiempo. «Recomendar ruta» calcula el orden más corto con las direcciones de tus alumnos.":
    "This is the order you follow and the one the system uses to alert each family on time. “Suggest route” works out the shortest order using your students' addresses.",
  "Calculando…": "Calculating…",
  "✨ Recomendar ruta": "✨ Suggest route",
  "✨ Ruta recomendada: {km} (antes {antes})": "✨ Suggested route: {km} (was {antes})",
  "Ahorras {km} por recorrido.": "You save {km} per trip.",
  "Calculada por calles con Google Maps.": "Calculated along streets with Google Maps.",
  "Calculada por distancia (aproximada).": "Calculated by distance (approximate).",
  "(antes {n}°)": "(was #{n})",
  "Aplicar": "Apply",
  "Listo: {ruta} quedó con el orden recomendado.": "Done: {ruta} now uses the suggested order.",
  "Descartar": "Dismiss",
  "👍 El orden actual ya es el más corto (≈ {km}).": "👍 The current order is already the shortest (≈ {km}).",
  "📅 Hoy no va · tocar si sí va": "📅 Not riding today · tap if they are",
  "Hoy no va": "Not riding today",
  "Todos los alumnos ya están en esta ruta.": "All students are already on this route.",
  "+ Agregar alumno a esta ruta": "+ Add student to this route",

  // Solicitudes
  "Pregunta": "Question",
  "Cancelación": "Cancellation",
  "Cambio de datos": "Update details",
  "Reclamo": "Complaint",
  "Otro": "Other",
  "Solicitudes": "Requests",
  "No hay solicitudes por atender. 🎉": "No requests to handle. 🎉",
  "Sin responder": "Unanswered",
  "Respondida": "Answered",
  "Solicitud": "Request",
  "Respuesta enviada.": "Reply sent.",
  "Escribe tu respuesta": "Write your reply",
  "Aprobar cancelación y dar de baja": "Approve cancellation and remove student",
  "Cancelación aprobada: el alumno salió de tus rutas.": "Cancellation approved: the student was removed from your routes.",
  "Solo responder": "Just reply",
  "Responder": "Reply",
  "Cerrar consulta": "Close request",
  "Consulta cerrada.": "Request closed.",
  "Cerrada · cancelación aprobada.": "Closed · cancellation approved.",
  "Cerrada · cancelación rechazada.": "Closed · cancellation declined.",

  // Administración en la web (admin/index.tsx)
  "La administración del furgón se hace en el panel web, desde el computador o el navegador del teléfono.":
    "School van management is done in the web panel, from a computer or your phone's browser.",
  "Esta app es para la tía o el tío del furgón y para las familias.": "This app is for school van drivers and families.",
  "Abrir el panel web": "Open the web panel",
  "Vencimiento: {fecha}": "Expires: {fecha}",
};
